<a href="https://colab.research.google.com/github/carljhon/Appsdev-prelim-exam/blob/master/3_Numpy_Array_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Indexing and Selection

In [ ]:
import numpy as np

In [ ]:
sample_array = np.arange(0, 11)

In [ ]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing Array

In [ ]:
sample_array[7]

7

In [ ]:
# Array slicing
sample_array[2:5]

In [ ]:
# Get everthing beyond index 2
sample_array[2:]

## Broadcasting in NumPy Array

In [ ]:
sample_array

In [ ]:
# Set the value of index 4 and 6 to 10
sample_array[4:6] = 10

In [ ]:
sample_array

## Copy an Array

In [ ]:
sample_array = np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
new_copy = sample_array.copy()

In [ ]:
new_copy[:3] = 10

In [ ]:
new_copy

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
sample_array

## Selection

# Activity
Get index of the lowest number

In [ ]:
array = np.random.randint(0, 100, 25)
two_dimensional = array.reshape(5, 5)

In [ ]:
two_dimensional

array([[96, 94, 37, 68,  9],
       [64, 72, 30, 51,  5],
       [35, 20, 33, 85, 52],
       [76, 59, 42, 64, 36],
       [23, 25, 71, 87, 38]])

In [ ]:
# your code goes here

In [ ]:
Sort = np.sort(array)
First = Sort[:1]

Output = np.where(two_dimensional == First)

Output

(array([1]), array([4]))